メーカー:
  農林・水産:
    - 水産
    - 農林
  食品:
    - 食品
  建設・設備関連:
    - 建設
    - 建築
    - 設備
  住宅・インテリア:
    - 住宅
    - 建材・エクステリア
    - ディスプレイ・空間デザイン
  化学・石油:
    - 化学
    - 石油
  繊維・紙・パルプ:
    繊維
    紙・パルプ
  薬品・化粧品:
    - 化粧品
    - 薬品
  ゴム・ガラス・セラミックス:
    - タイヤ・ゴム製品
    - セメント
    - ガラス・セラミックス
  鉄鋼・金属・鉱業:
    - 鉄鋼
    - 金属
    - 鉱業
  機械:
    - 機械
  プラント・エンジニアリング:
    - プラント・エンジニアリング
    - 環境・リサイクル
  電子・電気・OA機器:
    - 総合電機
    - 家電
    - 半導体・電子
    - 重電・産業用電気機器
    - その他電気・電子関連
    - コンピュータ・通信機器
  自動車・輸送用機器:
    - 自動車
    - 輸送機器
  精密・医療機器:
    - 精密機器
    - 医療機器
  印刷・事務機器・日用品:
    - 印刷関連
    - 文具・事務機器
    - 日用品・生活関連機器
  アパレル・服飾関連:
    - アパレル
    - 服飾雑貨・皮革製品
  スポーツ・玩具・ゲーム製品:
    ゲーム・アミューズメント
    スポーツ・レジャー用品
  その他メーカー・製造関連:
    - その他
    - 受託開発・特定技術派遣

商社:
  総合商社:
    - 総合商社
  専門商社:
    - 食品
    - 農林・水産
    - 石油
    - 化学
    - 化粧品
    - 薬品
    - 機械
    - 医療機器
    - 自動車・輸送機器
    - OA関連
    - 電気・電子
    - 金属
    - 建材・エクステリア
    - 紙
    - 繊維製品
    - アパレル
    - インテリア
    - スポーツ
    - 教育関連
    - グループ
    - その他

百貨店・ストア・専門店:
  百貨店・スーパー・コンビニ:
    - 百貨店
    - スーパー・ストア
    - コンビニエンスストア
    - ホームセンター
    - 流通・チェーンストア
    - 生活協同組合
  専門店:
    - 総合
    - ドラッグストア
    - メガネ
    - スポーツ
    -  自動車関連
    - 音楽・書籍・インテリア
    - アパレル
    -  繊維製品
    - 家電
    - 食品
    - その他

金融:
  銀行・証券:
    - 政府系・系統金融機関
    - 都市銀行
    - 地方銀行
    - 信託銀行
    - 証券
    - 金融総合グループ
  信金・労金・信組:
    - 信用金庫
    - 労働金庫
    - 信用組合
  クレジット・信販・リース・その他金融:
    - 外資系金融
    - クレジット・信販
    - 共済
    - リース・レンタル
    - 消費者金融
    - 商品取引
    - その他金融
  生保・損保:
    - 生命保険
    - 損害保険

サービス・インフラ:
  不動産:
    - 不動産
  鉄道・航空:
    - 鉄道
    - 航空
    - 空輸
  陸運・海運・物流:
    - 陸運
    - 海運
    - 倉庫
  電力・ガス・エネルギー:
    - 電気
    - ガス
    - 水道
    - エネルギー
  コンサルティング・調査:
    - シンクタンク
    - マーケティング・調査
    - コンサルタント
    - コンサルティングファーム
  レストラン・給食・フードサービス:
    - レストラン
    - 給食・デリカ
    - フード
  ホテル・旅行:
    - ホテル
    - 旅館
    - 旅行・観光
  医療機関・調剤薬局:
    - 医療
    - 調剤薬局
  福祉サービス:
    - 福祉
  フィットネスクラブ・エステ・理美容:
    - フィットネスクラブ
    - スポーツ・ヘルス関連施設
    - エステ
    - 美容・理容
  アミューズメント・レジャー:
    - レジャー
    - アミューズメント
  冠婚葬祭:
    - 冠婚葬祭
  人材サービス:
    - 人材派遣・人材紹介
    - 職業紹介・業務請負
  専門・その他サービス:
    - メンテナンス
    - 機械設計
    - 建築設計
    - 清掃事業
    - セキュリティ
    - 芸術
    - 芸能
    - 各種ビジネスサービス
    - フォトサービス
    - クリーニング
    - その他
  教育関連:
    - 教育
    - 学校法人
    - 幼稚園・保育園

広告・出版・マスコミ:
  マスコミ（放送・新聞）:
    - 放送
    - 新聞
  マスコミ（出版・広告）:
    - 出版
    - 広告
  芸能・エンタテインメント:
    - 芸能・エンタテインメント


ソフトウェア・情報処理・通信:
  ソフトウエア・情報処理・ネット関連:
    - ソフトウエア
    - 情報処理
    - インターネット関連
  ゲームソフト:
    - ゲームソフト
  通信:
    - 通信事業サービス
    - データ通信

官公庁・公社・団体:
  官公庁・公社:
    - 公社・官庁
    - 官公庁・警察
  団体:
    - 農業協同組合（JA金融機関含む）
    - 公益・特殊・独立行政法人
    - 団体・連合会
